---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-cluster-controller-clusterrole
rules:
  - apiGroups: ["", "events.k8s.io", "apps/v1", "apps", "admissionregistration.k8s.io/v1", "admissionregistration.k8s.io", "admissionregistration.k8s.io/v1beta1"]
    resources: ["events", "deployments", "validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-cluster-controller-rolebinding-cluster
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-cluster-controller-clusterrole
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ .Release.Name }}-controller-sa