import os

ENVIRONMENT_TYPE = os.getenv('ENV')
DEFAULT_CUSTOMER_ID = 777
PLACELESS_URL = os.getenv("PLACELESS_URL", "http://127.0.0.1:5000")
MYSQL_HOST = os.environ.get("PLACELESS_MYSQL_HOSTNAME")
MYSQL_USER = os.environ.get("PLACELESS_MYSQL_USERNAME")
MYSQL_PASSWORD = os.environ.get("PLACELESS_MYSQL_PASSWORD")
MYSQL_DB = os.environ.get("PLACELESS_MYSQL_DB")

